project_id = "hkohoumgswnyllcuragv"

[functions]
  [functions.ai-chat]
    verify_jwt = false
  [functions.analyze-gex]
    verify_jwt = false
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.historical-flow]
    verify_jwt = false
  [functions.polygon-proxy]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.run-backtest]
    verify_jwt = false
